# Generated by Django 5.2.14 on 2026-07-03 15:03

import django.core.validators
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('colors', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
