# Generated by Django 5.2.14 on 2026-07-23 12:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
