# Generated by Django 5.2.14 on 2026-07-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
