# Generated by Django 5.2.14 on 2026-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
