# Generated by Django 5.2.14 on 2026-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_admin',
            field=models.BooleanField(default=False),
        ),
    ]
