# Generated by Django 5.2.14 on 2026-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_verified_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
