# Generated by Django 5.2.14 on 2026-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='validity',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Year', 'Year'), ('Month', 'Month'), ('Week', 'Week'), ('Day', 'Day')], max_length=120, null=True),
        ),
    ]
