# Generated by Django 5.2.14 on 2026-07-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payments', '0003_subscriptionplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
