# Generated by Django 5.2.14 on 2026-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankname',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
