# Generated by Django 5.2.14 on 2026-06-30 16:24

import bank.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.IntegerField(default=bank.core.services.generate_account_number, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=255, null=True),
        ),
    ]
