# Generated by Django 5.2.14 on 2026-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_account_number_bankaccount_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
