# Generated by Django 5.2.14 on 2026-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
