# Generated by Django 5.2.14 on 2026-07-17 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_identification_reject_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity_verification', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'svg', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='identification',
            name='middle_mark_sheet',
            field=models.ImageField(blank=True, null=True, upload_to='identity_verification', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'svg', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='identification',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_verification', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'svg', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='identification',
            name='secondary_mark_sheet',
            field=models.ImageField(blank=True, null=True, upload_to='identity_verification', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'svg', 'jfif'])]),
        ),
    ]
