# Generated by Django 5.2.14 on 2026-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_audio_file_chatmessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
