# Generated by Django 5.2.14 on 2026-06-25 11:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='biograph',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
