# Generated by Django 5.2.14 on 2026-06-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_student_biograph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
    ]
