# Generated by Django 5.2.14 on 2026-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_student_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
